on:
  pull_request:
    branches:
      - master
      - main

jobs:
  test_install_phylum_job:
    runs-on: ubuntu-latest
    name: A job to test phylum analyze PR
    steps:
      - uses: actions/checkout@v2
      - id: analyze-pr-test
      #uses: peterjmorgan/phylum-analyze-pr-action@master
        uses: peterjmorgan/phylum-analyze-pr-action@v0.92
        with:
          vul_threshold: 0.6
          mal_threshold: 0.6
          eng_threshold: 0.6
          lic_threshold: 0.6
          aut_threshold: 0.6
          phylum_username: ${{ secrets.PHYLUM_USER }}
          phylum_password: ${{ secrets.PHYLUM_PASS }}
